<?php

/**
 * BaseClub
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $nombre
 * @property timestamp $aniversario_at
 * @property text $descripcion
 * @property text $region
 * @property text $ciudad
 * @property text $comuna
 * @property text $pais
 * @property text $url
 * @property text $email
 * @property integer $user_id
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $sfGuardUserProfile
 * @property Doctrine_Collection $ClubCandidate
 * 
 * @method varchar             getNombre()             Returns the current record's "nombre" value
 * @method timestamp           getAniversarioAt()      Returns the current record's "aniversario_at" value
 * @method text                getDescripcion()        Returns the current record's "descripcion" value
 * @method text                getRegion()             Returns the current record's "region" value
 * @method text                getCiudad()             Returns the current record's "ciudad" value
 * @method text                getComuna()             Returns the current record's "comuna" value
 * @method text                getPais()               Returns the current record's "pais" value
 * @method text                getUrl()                Returns the current record's "url" value
 * @method text                getEmail()              Returns the current record's "email" value
 * @method integer             getUserId()             Returns the current record's "user_id" value
 * @method sfGuardUser         getSfGuardUser()        Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getSfGuardUserProfile() Returns the current record's "sfGuardUserProfile" collection
 * @method Doctrine_Collection getClubCandidate()      Returns the current record's "ClubCandidate" collection
 * @method Club                setNombre()             Sets the current record's "nombre" value
 * @method Club                setAniversarioAt()      Sets the current record's "aniversario_at" value
 * @method Club                setDescripcion()        Sets the current record's "descripcion" value
 * @method Club                setRegion()             Sets the current record's "region" value
 * @method Club                setCiudad()             Sets the current record's "ciudad" value
 * @method Club                setComuna()             Sets the current record's "comuna" value
 * @method Club                setPais()               Sets the current record's "pais" value
 * @method Club                setUrl()                Sets the current record's "url" value
 * @method Club                setEmail()              Sets the current record's "email" value
 * @method Club                setUserId()             Sets the current record's "user_id" value
 * @method Club                setSfGuardUser()        Sets the current record's "sfGuardUser" value
 * @method Club                setSfGuardUserProfile() Sets the current record's "sfGuardUserProfile" collection
 * @method Club                setClubCandidate()      Sets the current record's "ClubCandidate" collection
 * 
 * @package    motoadicto
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClub extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('club');
        $this->hasColumn('nombre', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('aniversario_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('region', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('ciudad', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('comuna', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('pais', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('url', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('email', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('sfGuardUserProfile', array(
             'local' => 'id',
             'foreign' => 'club_id'));

        $this->hasMany('ClubCandidate', array(
             'local' => 'id',
             'foreign' => 'club_id'));

        $jcroppable0 = new Doctrine_Template_JCroppable(array(
             'images' => 
             array(
              0 => 'logo',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'unique' => true,
             ));
        $this->actAs($jcroppable0);
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}