<?php

/**
 * BaseClubCandidate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $club_id
 * @property integer $user_id
 * @property Club $club
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer       getClubId()      Returns the current record's "club_id" value
 * @method integer       getUserId()      Returns the current record's "user_id" value
 * @method Club          getClub()        Returns the current record's "club" value
 * @method sfGuardUser   getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method ClubCandidate setClubId()      Sets the current record's "club_id" value
 * @method ClubCandidate setUserId()      Sets the current record's "user_id" value
 * @method ClubCandidate setClub()        Sets the current record's "club" value
 * @method ClubCandidate setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    motoadicto
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClubCandidate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('club_candidate');
        $this->hasColumn('club_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('candidate_index', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'club_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Club as club', array(
             'local' => 'club_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}