<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property varchar $rut
 * @property timestamp $nacimiento_at
 * @property boolean $sexo
 * @property text $direccion
 * @property text $ciudad
 * @property text $comuna
 * @property text $region
 * @property text $pais
 * @property text $telefono
 * @property text $sitio_web
 * @property integer $club_id
 * @property sfGuardUser $sfGuardUser
 * @property Club $Club
 * 
 * @method integer            getUserId()        Returns the current record's "user_id" value
 * @method varchar            getRut()           Returns the current record's "rut" value
 * @method timestamp          getNacimientoAt()  Returns the current record's "nacimiento_at" value
 * @method boolean            getSexo()          Returns the current record's "sexo" value
 * @method text               getDireccion()     Returns the current record's "direccion" value
 * @method text               getCiudad()        Returns the current record's "ciudad" value
 * @method text               getComuna()        Returns the current record's "comuna" value
 * @method text               getRegion()        Returns the current record's "region" value
 * @method text               getPais()          Returns the current record's "pais" value
 * @method text               getTelefono()      Returns the current record's "telefono" value
 * @method text               getSitioWeb()      Returns the current record's "sitio_web" value
 * @method integer            getClubId()        Returns the current record's "club_id" value
 * @method sfGuardUser        getSfGuardUser()   Returns the current record's "sfGuardUser" value
 * @method Club               getClub()          Returns the current record's "Club" value
 * @method sfGuardUserProfile setUserId()        Sets the current record's "user_id" value
 * @method sfGuardUserProfile setRut()           Sets the current record's "rut" value
 * @method sfGuardUserProfile setNacimientoAt()  Sets the current record's "nacimiento_at" value
 * @method sfGuardUserProfile setSexo()          Sets the current record's "sexo" value
 * @method sfGuardUserProfile setDireccion()     Sets the current record's "direccion" value
 * @method sfGuardUserProfile setCiudad()        Sets the current record's "ciudad" value
 * @method sfGuardUserProfile setComuna()        Sets the current record's "comuna" value
 * @method sfGuardUserProfile setRegion()        Sets the current record's "region" value
 * @method sfGuardUserProfile setPais()          Sets the current record's "pais" value
 * @method sfGuardUserProfile setTelefono()      Sets the current record's "telefono" value
 * @method sfGuardUserProfile setSitioWeb()      Sets the current record's "sitio_web" value
 * @method sfGuardUserProfile setClubId()        Sets the current record's "club_id" value
 * @method sfGuardUserProfile setSfGuardUser()   Sets the current record's "sfGuardUser" value
 * @method sfGuardUserProfile setClub()          Sets the current record's "Club" value
 * 
 * @package    motoadicto
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('rut', 'varchar', 12, array(
             'type' => 'varchar',
             'notnull' => false,
             'unique' => true,
             'length' => 12,
             ));
        $this->hasColumn('nacimiento_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('sexo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('direccion', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('ciudad', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('comuna', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('region', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('pais', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('telefono', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('sitio_web', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('club_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Club', array(
             'local' => 'club_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $jcroppable0 = new Doctrine_Template_JCroppable(array(
             'images' => 
             array(
              0 => 'avatar',
             ),
             ));
        $this->actAs($jcroppable0);
    }
}