<?php

/**
 * Club
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    motoadicto
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Club extends BaseClub
{
  public function getOwner(){
    return $this->getUserId();
  }
  public function isOwner($user_id){
    if($user_id == $this->getUserId()) return true;
    else return false;
  }
  public function hasComuna(){
    if($this->getComuna() == null || $this->getComuna() == '') return false;
    else return true;
  }
  public function hasRegion(){
    if($this->getRegion() == null || $this->getRegion() == '') return false;
    else return true;
  }
  public function hasUrl(){
    if($this->getUrl() == null || $this->getUrl() == '') return false;
    else return true;
  }
  public function hasDescripcion(){
    if($this->getDescripcion() == null || $this->getDescripcion() == '') return false;
    else return true;
  }
  public function getMiembros(){
    $miembros = Doctrine_Core::getTable('sfGuardUserProfile')->createQuery()
            ->where('club_id = ?',$this->getId())
            ->execute();
    return $miembros;
  }
  public function getCandidatos(){
    $candidatos = Doctrine_Core::getTable('ClubCandidate')->createQuery()
            ->where('club_id = ?',$this->getId())
            ->execute();
    return $candidatos;
  }
}
