<?php

/**
 * ClubTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClubTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClubTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Club');
    }
}