<?php

/**
 * ClubCandidateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClubCandidateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClubCandidateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClubCandidate');
    }
}