<?php

/**
 * sfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    motoadicto
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
  public function hasClub(){
    if($this->getClubId() == null){
      return false;
    } else return true;
  }
  public function hasProfile(){
    if($this->getProfile()){
      return false;
    } else return true;
  }
  public function isCandidate(){
    $q = Doctrine::getTable('ClubCandidate')->findOneByUserId($this->getUserId());
    if($q) return true;
    else return false;
  }
  public function getAge()
  {
    $birthDate = new DateTime($this->getNacimientoAt());
    $now = new DateTime();
    $interval = $now->diff($birthDate);
    return $interval->y;
  }
}
