# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:

all:
  recaptcha:
      private_key: 6Le3t84SAAAAALrPnl5c00mGonA3wWr4ARKcGdio
      public_key:  6Le3t84SAAAAAPhbXnz0IDXy4EBrj3jwUf-hyhIn
  
  sf_guard_plugin:
      remember_key_expiration_age:  2592000   # 30 days in seconds
      remember_cookie_name:         MotoAdicto
      success_signin_url:      @homepage # the plugin use the referer as default
      success_signout_url:     @homepage         # the plugin use the referer as default
  
  sfImageTransformPlugin:
    default_adapter:  GD
    mime_type:
      auto_detect:    true
      library:        gd_mime_type
  
  sfDoctrineJCroppablePlugin:
    models:
      Banner:
        directory:      images/Banner
        images:
          slide:
            padding:    { percent: 0, color: "#ffffff" }
            ratio:      3.066666667
            sizes:
              banner:   { width: 920 }
              mini:     { width: 230 }
      SfGuardUserProfile:
        directory:      images/avatar
        images:
          avatar:
            padding:    { percent: 0, color: "#ffffff" }
            ratio:      0.989795918
            sizes:
              normal:   { width: 97 }
              mini:     { width: 50 }
      Club:
        directory:      images/Club
        images:
          logo:
            padding:    { percent: 0, color: "#ffffff" }
            ratio:      0.989795918
            sizes:
              grande:   { width: 172 }
              normal:   { width: 97 }
              mini:     { width: 50 }
  
  max_width:            1024
