# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

club_new:
  url:     /club/new
  class:   sfDoctrineRoute
  options: { model: Club, type: object }
  param:   { module: club, action: new }
  requirements: { sf_method: get }

club_edit:
  url:     /club/edit
  class:   sfDoctrineRoute
  options: { model: Club, type: object }
  param:   { module: club, action: edit }
  requirements: { sf_method: get }

club_ListMiembros:
  url:     /club/ListMiembros
  class:   sfDoctrineRoute
  options: { model: Club, type: object }
  param:   { module: club, action: ListMiembros }
  requirements: { sf_method: get }

club_delete:
  url:     /club/delete/:id
  class:   sfDoctrineRoute
  options: { model: Club, type: object }
  param:   { module: club, action: delete }
  requirements: { sf_method: delete }

club_EditLogo:
  url:     /club/EditLogo
  class:   sfDoctrineRoute
  options: { model: Club, type: object }
  param:   { module: club, action: EditLogo }
  requirements: { sf_method: get }

club_show:
  url:     /club/:slug
  class:   sfDoctrineRoute
  options: { model: Club, type: object }
  param:   { module: club, action: show }
  requirements:
    slud: \w+
    sf_method: [get]

club_submit:
  url:     /club/:slug/submit
  class:   sfDoctrineRoute
  options: { model: Club, type: object }
  param:   { module: club, action: submit }
  requirements:
    slud: \w+
    sf_method: [get]

user_profile_club:
  url:     /user/ProfileClub
  class:   sfDoctrineRoute
  options: { model: UserProfile, type: object }
  param:   { module: user, action: ProfileClub }
  requirements: { sf_method: get }

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }