# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        MotoAdicto.cl
    #description:  symfony project
    #keywords:     symfony, project
    language:     es
    robots:       index, follow

  stylesheets:
    - 88100.css
    - anythingslider_59edcbff.css
    - prettyphoto_59edcbff.css
    - style_59edcbff.css
    - rainbow_59edcbff.css

  javascripts:
    - jquery/jquery-1.5.2.min.js
    - cufon-yui.js
    - bebas-neue.cufonfonts.js
    - jquery.timers-1.2.js
    - jquery.easing.1.3.js
    - swfobject.js
    - jquery.anythingslider.min.js
    - hoverintent.js
    - superfish.js
    - jquery.color.js
    - jquery.prettyphoto.js
    - script_59edcbff.js
    - modernizr-1.5.min.js
    
  has_layout:     true
  layout:         layout
